web/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"   


urlpatterns = [
    path('', views.blog, name="blogs"),
    
    path('home/', views.HomePageView.as_view(), name="home"), # Notice the URL has been named
    path('about/', views.AboutPageView.as_view(), name='about'),
    path('cloud/', views.CloudView.as_view(), name='cloud'),
]

web/django_k8s/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings #add this
from django.conf.urls.static import static #add this

urlpatterns = [
    path('', include ('blog.urls')),
    path('admin/', admin.site.urls),
]

# #DEV ONLY
# if settings.DEBUG: 
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/blog/models.py
from django.db import models

class Blog(models.Model):
	blog_title = models.CharField(max_length=150)
	blog_url = models.CharField(max_length=150, null=True, blank=True)
	release_date = models.CharField(max_length=15)
	writer = models.CharField(max_length=100)
	blog_detail = models.TextField()
	# file will be uploaded to MEDIA_ROOT / images
	blog_photo = models.ImageField(upload_to ='uploads/', blank=True, 
	                               null=True, default='media/uploads/k8s.png')
    
	def __str__(self):
		return self.blog_title

web/blog/views.py
from django.shortcuts import render
from .models import Blog
from django.views.generic import TemplateView # Import TemplateView

# Create your views here.
def blog(request):
	blogs = Blog.objects.all() #queryset containing all movies we just created
	return render(request=request, template_name="blog/blogs.html", context={'blogs':blogs})

# Add the two views we have been talking about  all this time :)
class HomePageView(TemplateView):
    template_name = "blog/index.html"


class AboutPageView(TemplateView):
    template_name = "blog/about.html"


class CloudView(TemplateView):
    template_name = "blog/cloud.html"

web/blog/templates/blog/about.html
{% extends 'blog/base.html' %} <!-- Add this for inheritance -->

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}About Us {% endblock %}</title>
</head>
<body>
  {% block pagecontent %}
  <p>
  <h1><font color="teal">
      ********TESTING PAGE *************<br>
      ***********DESIGNED IN DJANGO.*******<BR>
      ******** By S Paul ******************<br>
  </font></h1>
  <h2><font color="teal">
      Different technical blogs link have been provided for easy access which will help you during the learning phase of different technologies like:
  </font></h2>
  <font size=5 color="blue">
  <ol>
    <li>Django</li>
    <li>Jenkins</li>
    <li>Ansible</li>
    <li>Python</li>
    <li>Kubernetes</li>
  </ol>
  </font>
  </p>
  
  {% endblock %}
</body>
</html>

web/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>
      Site - {% block title %}{% endblock %}
    </title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="{% static 'js/main.js' %}"></script> <!-- This is how to include a static file -->
    {% comment %} <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" /> {% endcomment %}
    
</head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url 'blog:blogs' %}">Blogs</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:cloud' %}">Cloud Technologies </a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'blog:about' %}">About</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Links
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Kubernetes</a>
          <a class="dropdown-item" href="#">Python</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">CICD implementation</a>
        </div>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Type here" aria-label="Search">
      <button class="btn btn btn-warning my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
<hr>
<p></p>
    <div class="container">
    
      {% block pagecontent %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>

web/blog/templates/blog/blogs.html
{% extends 'blog/base.html' %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Tech Blogs {% endblock %}</title>
    <!--Bootstrap CSS-->
    {% comment %} <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}" type="text/css" />
  </head>
  <body>
     {% block pagecontent %}
    
    <div class="container p-4">
      <div class="row">
        {% for m in blogs %}
        <div class="col-lg-4 col-md-6 col-sm-12 pb-4">
          <div class="card h-100 p-4">
            {% if m.blog_photo %}
              <p><img src="{{ m.blog_photo.url }}" class="card-img-top" alt="{{ m.blog_title}}" style="width: 300px; height: 100px; object-fit: contain;"></p>
              {% else %}
              <p></p>
            {% endif %}
            
            <h4><a href={{m.blog_url}} target="_blank" rel="noopener noreferrer">{{m.blog_title}}</a></h4>
            <p class="text-muted">{{m.release_date}} | {{m.writer}}</p>
            <p>{{m.blog_detail}}</p>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>

  {% endblock %}    
  </body>
</html>

web/blog/templates/blog/cloud.html
{% extends 'blog/base.html' %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}Cloud Technology {% endblock %}</title>
</head>
<body>
  {% block pagecontent %}
      <div class="container">
        <section class="blog-trio-post__section">
          <div id="trio-post-body" class="blog-trio-post__body">

<h2 id="markdown-WhatIsCloudTechnology">What Is Cloud Technology?</h2>
<p>Cloud computing encompasses technologies that allow individuals or businesses access to certain data or services without the need for physical infrastructure.&nbsp;</p>
<p><strong>There are a few popular cloud technology categories such as<span>&nbsp;</span></strong><span><strong>infrastructure as a service (IaaS); communication as a service (CaaS); and software as a service (SaaS).</strong></span></p>
<p>&nbsp;</p>
<figure><img src="https://www.trio.dev/hs-fs/hubfs/iaas-caas-saas.jpg?width=600&amp;name=iaas-caas-saas.jpg" alt="&quot;&quot;" width="600" loading="lazy" style="width: 600px;" srcset="https://www.trio.dev/hs-fs/hubfs/iaas-caas-saas.jpg?width=300&amp;name=iaas-caas-saas.jpg 300w, https://www.trio.dev/hs-fs/hubfs/iaas-caas-saas.jpg?width=600&amp;name=iaas-caas-saas.jpg 600w, https://www.trio.dev/hs-fs/hubfs/iaas-caas-saas.jpg?width=900&amp;name=iaas-caas-saas.jpg 900w, https://www.trio.dev/hs-fs/hubfs/iaas-caas-saas.jpg?width=1200&amp;name=iaas-caas-saas.jpg 1200w, https://www.trio.dev/hs-fs/hubfs/iaas-caas-saas.jpg?width=1500&amp;name=iaas-caas-saas.jpg 1500w, https://www.trio.dev/hs-fs/hubfs/iaas-caas-saas.jpg?width=1800&amp;name=iaas-caas-saas.jpg 1800w" sizes="(max-width: 600px) 100vw, 600px"></figure>
<p><strong>Let's break down each one of the categories.</strong></p>
<h3>IaaS</h3>
<p><strong>IaaS is one of the root forms of cloud computing.<span>&nbsp;</span></strong>This is because IaaS provides network infrastructure like servers and storage. Businesses like yours can avoid investing in on-site resources and outsource this need to an IaaS provider.&nbsp;</p>
<p><a href="https://trio.dev/aws">Amazon Web Services (AWS)</a><span>&nbsp;</span>is likely the most pervasive example of IaaS. While it’s likely more people are familiar with the online shopping website, AWS is a cloud platform hosting data centers globally that powers much of the internet.&nbsp;</p>
<p>Jeff Bezos compares AWS to a utility company. In the early 1900s, a factory needing electricity would need to build its own power plant. Of course, this was until electric companies made it possible for others to buy electricity as a public utility.&nbsp;</p>
<p>Similarly, AWS serves as a storage space for<span>&nbsp;</span><a href="https://www.investopedia.com/articles/investing/011316/what-amazon-web-services-and-why-it-so-successful.asp">more than a third</a><span>&nbsp;</span>of the cloud market. For small and medium-sized businesses (SMBs) especially, this can be a practical way of reducing startup costs.&nbsp;</p>
<h3>CaaS</h3>
<p><strong>CaaS is something most people are familiar with, even if the term ‘CaaS’ isn’t the first thing to come to mind.</strong></p>
<p>Communication mediums like instant messaging,<span>&nbsp;</span><a href="https://callhippo.com/blog/industry/voip-solution-for-different-industries">Voice over Internet Protocol or VoIP technology</a>, video conferencing, and more all fit neatly under the category of CaaS.&nbsp;&nbsp;</p>
<p>You probably don’t need any help to think of a bunch of CaaS examples in action. These examples may include Skype, Facebook Messenger, Discord, Slack, etc.&nbsp;</p>
<p>Whatever hardware and software are responsible for delivering these services is largely behind the scenes while you reap the benefits.&nbsp;</p>
<h3>SaaS</h3>
<p><strong>With SaaS, businesses can access software on a subscription basis.</strong></p>
<p>SaaS providers carry the burden of maintaining and storing servers, databases, and the code that makes up the application. All you need is an internet connection. Some salient examples of SaaS might be Microsoft 365 or Dropbox.&nbsp;</p>
<p>Microsoft 365 lends you all the products of the Microsoft Office Suite that are often installed on one’s computer. Except with Microsoft 365, it can be utilized from your web browser, no installation required.</p>
<p>Dropbox is a storage service where you can save documents, pictures, and videos online. The advantage gained is that if you lose media on your local device, you will always have a backup online so long as you have an internet connection.&nbsp;</p>

          </div>
  
  
  {% endblock %}
</body>
</html>

web/blog/templates/blog/home.html
{% extends 'main/header.html' %}

  {% block content %}

  {% load static %}  #load static


   <div class="container">
     <img class="img-fluid" src="{% static 'image/self.png' %}" alt="photo">
   </div>


  {% endblock %}